image: gitlab-registry.cern.ch/pseyfert/lxplus-like-dockerfile

note:
    script:
      - make
    artifacts:
      paths:
        - main.pdf

spellcheck:
    script:
      - touch spelling-mistakes.txt
      - make batch-spellcheck -k -j 1
      - sort -u -o spelling-mistakes.txt spelling-mistakes.txt
    artifacts:
      paths:
        - spelling-mistakes.txt